--------------------------------------------------------------------------------------
-- Name	       : SD (Sample Database) for Oracle Tutorial
--------------------------------------------------------------------
-- Execute the following statements to create a user name SD and
-- grant priviledges
--------------------------------------------------------------------

-- create new user
CREATE USER SD IDENTIFIED BY admin123;

-- grant priviledges
GRANT CONNECT, RESOURCE, DBA TO SD;

GRANT CREATE SESSION TO SD;

GRANT UNLIMITED TABLESPACE TO SD;
COMMIT;


-- customers
CREATE TABLE customers_data
  (
    customer_id_pk NUMBER 
                GENERATED BY DEFAULT AS IDENTITY START WITH 320 
                PRIMARY KEY,
    name         VARCHAR2( 255 ) NOT NULL,
    address      VARCHAR2( 255 )         ,
    website      VARCHAR2( 255 )         ,
    credit_limit NUMBER( 8, 2 )
  );

  -- orders table
CREATE TABLE orders_data
  (
    order_id_pk NUMBER 
             GENERATED BY DEFAULT AS IDENTITY START WITH 106 
             PRIMARY KEY,
    customer_id NUMBER( 6, 0 ) NOT NULL, 
    status      VARCHAR( 20 ) NOT NULL ,
    salesman_id NUMBER( 6, 0 )         , 
    order_date  DATE NOT NULL          
  );

-- INSERTING into OT.customers_data
Insert into SD.customers_data (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (101,'United Continental Holdings','2904 S Salina St, Syracuse, NY',5000,'http://www.unitedcontinentalholdings.com');
Insert into SD.customers_data (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (102,'INTL FCStone','5344 Haverford Ave, Philadelphia, PA',5000,'http://www.intlfcstone.com');
Insert into SD.customers_data (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (103,'Publix Super Markets','1795 Wu Meng, Muang Chonburi, ',1200,'http://www.publix.com');
Insert into SD.customers_data (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (104,'ConocoPhillips','Walpurgisstr 69, Munich, ',2400,'http://www.conocophillips.com');
Insert into SD.customers_data (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (105,'3M','Via Frenzy 6903, Roma, ',1200,'http://www.3m.com');
Insert into SD.customers_data (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (106,'Exelon','Via Luminosa 162, Firenze, ',500,'http://www.exeloncorp.com');
Insert into SD.customers_data (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (107,'Tesoro','Via Notoriosa 1942, Firenze, ',500,'http://www.tsocorp.com');
Insert into SD.customers_data (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (108,'Northwestern Mutual','1831 No Wong, Peking, ',3600,'http://www.northwesternmutual.com');
Insert into SD.customers_data (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (109,'Enterprise Products Partners','Via Notoriosa 1949, Firenze, ',2400,'http://www.enterpriseproducts.com');
Insert into SD.customers_data (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (110,'Rite Aid','Piazza Cacchiatore 23, San Giminiano, ',3600,'http://www.riteaid.com');
Insert into SD.customers_data (CUSTOMER_ID,NAME,ADDRESS,CREDIT_LIMIT,WEBSITE) values (111,'Qualcomm','Piazza Svizzera, Milano, ',500,'http://www.qualcomm.com');

-- INSERTING into OT.orders_data
Insert into SD.orders_data (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (1,101,'Pending',54,to_date('17-NOV-16','DD-MON-RR'));
Insert into SD.orders_data (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (2,102,'Pending',55,to_date('20-FEB-17','DD-MON-RR'));
Insert into SD.orders_data (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (3,103,'Pending',55,to_date('03-JAN-17','DD-MON-RR'));
Insert into SD.orders_data (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (4,104,'Pending',56,to_date('15-OCT-17','DD-MON-RR'));
Insert into SD.orders_data (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (5,105,'Canceled',56,to_date('09-APR-17','DD-MON-RR'));
Insert into SD.orders_data (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (6,106,'Canceled',57,to_date('15-AUG-17','DD-MON-RR'));
Insert into SD.orders_data (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (7,107,'Canceled',57,to_date('01-DEC-16','DD-MON-RR'));
Insert into SD.orders_data (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (8,108,'Shipped',59,to_date('09-APR-15','DD-MON-RR'));
Insert into SD.orders_data (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (9,109,'Shipped',59,to_date('11-MAY-17','DD-MON-RR'));
Insert into SD.orders_data (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (10,110,'Shipped',60,to_date('03-DEC-16','DD-MON-RR'));
Insert into SD.orders_data (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (11,111,'Shipped',61,to_date('20-DEC-16','DD-MON-RR'));