-- --------------------------------------------------
-- INDEX CODE STARTS
-- --------------------------------------------------

-- Database Index


CREATE DATABASE IF NOT EXISTS testIndexDB;

USE testIndexDB;

-- CREATE a NEW TABLE

CREATE TABLE IF NOT EXISTS COUNTRYDETAILS(
id INTEGER,
COUNTRY VARCHAR(20),
CONTINENT VARCHAR(20),
INDEX (COUNTRY, CONTINENT),
INDEX(COUNTRY),
Index (CONTINENT)
);

DESCRIBE COUNTRYDETAILS;

-- Insert Data Into Index Table

INSERT INTO COUNTRYDETAILS (id, COUNTRY, CONTINENT) VALUES (1,'Nepal', 'Asia');
INSERT INTO COUNTRYDETAILS (id, COUNTRY, CONTINENT) VALUES (2,'China', 'Asia');
INSERT INTO COUNTRYDETAILS (id, COUNTRY, CONTINENT) VALUES (3,'USA', 'North America');
INSERT INTO COUNTRYDETAILS (id, COUNTRY, CONTINENT) VALUES (4,'Mexico', 'North America');
INSERT INTO COUNTRYDETAILS (id, COUNTRY, CONTINENT) VALUES (5,'Canada', 'North America');
INSERT INTO COUNTRYDETAILS (id, COUNTRY, CONTINENT) VALUES (6,'Sri Lanka', 'Asia');


SELECT * FROM COUNTRYDETAILS;



-- Displays the Index from the Table
SHOW INDEX FROM COUNTRYDETAILS;